spring:
  application:
    name: DBOlimpoBeta

  datasource:
    url: jdbc:postgresql://localhost:5432/DBOlimpoBeta
    username: fabrica
    password: "fabrica2024*"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  main:
    allow-circular-references: true